tap "homebrew/cask"
tap "r-lib/rig"

brew "docker"
brew "gnupg"
brew "gcc"
brew "r"
brew "ruby"
brew "zsh"
brew "pdm"
brew "pipx"
brew "zsh-syntax-highlighting"

cask "calibre"
cask "dropbox"
cask "google-chrome"
cask "git-credential-manager"
cask "inkscape"
cask "iterm2"
cask "jabref"
cask "keepassxc"
cask "miniconda"
cask "rig"
cask "visual-studio-code"
cask "rstudio"
cask "spotify"
cask "zoom"
